name: Java CI with Gradle

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set Gradlew Permissions
        run: chmod +x ./gradlew
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '23'
      - name: Build with Gradle
        run: ./gradlew build
      - name: Run Tests
        run: ./gradlew test
